// This file is @generated by prost-build.
/// Node represents a single node in the Raft cluster
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Node {
    /// Unique identifier for the node
    #[prost(uint64, tag = "1")]
    pub node_id: u64,
    /// RPC address for node communication
    #[prost(string, tag = "2")]
    pub rpc_addr: ::prost::alloc::string::String,
}
/// LeaderId represents the leader identifier in Raft
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LeaderId {
    #[prost(uint64, tag = "1")]
    pub term: u64,
    #[prost(uint64, tag = "2")]
    pub node_id: u64,
}
/// Vote represents the voting information in Raft leader election
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Vote {
    #[prost(message, optional, tag = "1")]
    pub leader_id: ::core::option::Option<LeaderId>,
    #[prost(bool, tag = "2")]
    pub committed: bool,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Entry {
    #[prost(uint64, tag = "1")]
    pub term: u64,
    #[prost(uint64, tag = "2")]
    pub index: u64,
    /// 对应EntryType
    #[prost(uint32, tag = "3")]
    pub entry_type: u32,
    /// Optional Application data
    #[prost(bytes = "vec", tag = "4")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    /// Optional Membership config
    #[prost(message, optional, tag = "5")]
    pub membership: ::core::option::Option<Membership>,
}
/// NodeIds is a set of NodeIds
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NodeIdSet {
    #[prost(map = "uint64, message", tag = "1")]
    pub node_ids: ::std::collections::HashMap<u64, ()>,
}
/// Membership config
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Membership {
    /// Joint(includes more than one NodeIdSet) or uniform(one NodeIdSet) config.
    #[prost(message, repeated, tag = "1")]
    pub configs: ::prost::alloc::vec::Vec<NodeIdSet>,
    /// All of the nodes in the cluster, including voters and learners.
    /// A node id that is included in `configs` is a voter, otherwise it is a learner.
    #[prost(map = "uint64, message", tag = "2")]
    pub nodes: ::std::collections::HashMap<u64, Node>,
}
/// LogId represents the log identifier in Raft
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LogId {
    #[prost(uint64, tag = "1")]
    pub term: u64,
    #[prost(uint64, tag = "2")]
    pub index: u64,
}
/// VoteReq represents a request for votes during leader election
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VoteReq {
    #[prost(message, optional, tag = "1")]
    pub vote: ::core::option::Option<Vote>,
    #[prost(message, optional, tag = "2")]
    pub last_log_id: ::core::option::Option<LogId>,
}
/// VoteRsp represents the response to a vote request
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VoteRsp {
    #[prost(message, optional, tag = "1")]
    pub vote: ::core::option::Option<Vote>,
    #[prost(bool, tag = "2")]
    pub vote_granted: bool,
    #[prost(message, optional, tag = "3")]
    pub last_log_id: ::core::option::Option<LogId>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AppendEntriesReq {
    /// The leader's vote, used to identify the leader, and must be committed
    #[prost(message, optional, tag = "1")]
    pub vote: ::core::option::Option<Vote>,
    /// The previous log id the leader has sent to the follower
    #[prost(message, optional, tag = "2")]
    pub prev_log_id: ::core::option::Option<LogId>,
    /// The entries to be appended to the follower's log
    #[prost(message, repeated, tag = "3")]
    pub entries: ::prost::alloc::vec::Vec<Entry>,
    /// The leader's last committed log id
    #[prost(message, optional, tag = "4")]
    pub leader_commit: ::core::option::Option<LogId>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AppendEntriesRsp {
    /// If not None, the follower rejected the AppendEntries request due to having a higher vote.
    /// All other fields are valid only when this field is None
    #[prost(message, optional, tag = "1")]
    pub rejected_by: ::core::option::Option<Vote>,
    /// The follower accepts this AppendEntries request's vote, but the prev_log_id conflicts with
    /// the follower's log. The leader should retry with a smaller prev_log_id that matches the
    /// follower's log.
    ///
    /// For unary AppendEntries, `last_log_id` is not used for conflicts.
    /// For StreamAppend (pipeline replication), `last_log_id` carries the conflict log id.
    #[prost(bool, tag = "2")]
    pub conflict: bool,
    /// If `conflict = false`, the last log id the follower accepted from this request:
    ///
    /// * None: all input entries were accepted and persisted.
    /// * Some: partial success; only entries up to and including this id were accepted.
    ///
    /// If `conflict = true` in StreamAppend, this is the conflict log id.
    #[prost(message, optional, tag = "3")]
    pub last_log_id: ::core::option::Option<LogId>,
}
/// The first chunk of snapshot transmission, which contains the snapshot meta.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SnapshotReqMeta {
    #[prost(message, optional, tag = "1")]
    pub vote: ::core::option::Option<Vote>,
    #[prost(message, optional, tag = "2")]
    pub last_log_id: ::core::option::Option<LogId>,
    #[prost(message, optional, tag = "3")]
    pub last_membership_log_id: ::core::option::Option<LogId>,
    #[prost(message, optional, tag = "4")]
    pub last_membership: ::core::option::Option<Membership>,
    #[prost(string, tag = "5")]
    pub snapshot_id: ::prost::alloc::string::String,
}
/// The item of snapshot chunk stream.
///
/// The first item contains `meta`, including the leader vote and snapshot-meta.
///
/// Since the second item, the chunk contains the snapshot data.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SnapshotReq {
    #[prost(oneof = "snapshot_req::Payload", tags = "1, 2")]
    pub payload: ::core::option::Option<snapshot_req::Payload>,
}
/// Nested message and enum types in `SnapshotReq`.
pub mod snapshot_req {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Payload {
        #[prost(message, tag = "1")]
        Meta(super::SnapshotReqMeta),
        #[prost(bytes, tag = "2")]
        Chunk(::prost::alloc::vec::Vec<u8>),
    }
}
/// SnapshotRsp
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SnapshotRsp {
    #[prost(message, optional, tag = "1")]
    pub vote: ::core::option::Option<Vote>,
}
/// All the data in a state machine, including user defined data and membership data.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StateMachineData {
    /// The last log id that has been applied to the state machine
    #[prost(message, optional, tag = "1")]
    pub last_applied: ::core::option::Option<LogId>,
    /// User data in a map
    #[prost(map = "string, string", tag = "2")]
    pub data: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// The id of the last membership config log entry that is applied.
    #[prost(message, optional, tag = "3")]
    pub last_membership_log_id: ::core::option::Option<LogId>,
    /// The last membership config that is applied.
    #[prost(message, optional, tag = "4")]
    pub last_membership: ::core::option::Option<Membership>,
}
/// ========================= Control Plane ============================
/// InitReq contains the initial set of nodes for cluster initialization
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InitReq {
    /// List of initial cluster nodes
    #[prost(message, repeated, tag = "1")]
    pub nodes: ::prost::alloc::vec::Vec<Node>,
}
/// AddLearnerReq specifies parameters for adding a learner node
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AddLearnerReq {
    /// Node to be added as a learner
    #[prost(message, optional, tag = "1")]
    pub node: ::core::option::Option<Node>,
}
/// ChangeMembershipReq specifies parameters for modifying cluster membership
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ChangeMembershipReq {
    /// New set of voter node IDs
    #[prost(uint64, repeated, tag = "1")]
    pub members: ::prost::alloc::vec::Vec<u64>,
    /// Whether to retain existing configuration
    #[prost(bool, tag = "2")]
    pub retain: bool,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MembershipRsp {
    /// The log id of the committed log entry.
    #[prost(message, optional, tag = "1")]
    pub log_id: ::core::option::Option<LogId>,
    /// If the committed log entry is a change-membership entry.
    #[prost(message, optional, tag = "3")]
    pub membership: ::core::option::Option<Membership>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MetricsRsp {
    /// Cluster membership config
    #[prost(message, optional, tag = "1")]
    pub membership: ::core::option::Option<Membership>,
    /// In this example, only membership is used.
    /// Other metrics are just encoded in string for simplicity.
    /// In real-world scenarios, metrics should be encoded in a more structured format.
    #[prost(string, tag = "2")]
    pub other_metrics: ::prost::alloc::string::String,
}
/// Input to state machine operation
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AppStateMachineInput {
    /// User defined application data
    #[prost(bytes = "vec", tag = "1")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
/// Result from state machine operation
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AppStateMachineOutput {
    /// Result data from state machine operation
    #[prost(bytes = "vec", tag = "1")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum EntryType {
    UnknownType = 0,
    Blank = 1,
    Normal = 2,
    Membership = 3,
}
impl EntryType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::UnknownType => "UNKNOWN_TYPE",
            Self::Blank => "BLANK",
            Self::Normal => "NORMAL",
            Self::Membership => "MEMBERSHIP",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNKNOWN_TYPE" => Some(Self::UnknownType),
            "BLANK" => Some(Self::Blank),
            "NORMAL" => Some(Self::Normal),
            "MEMBERSHIP" => Some(Self::Membership),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod raft_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// InternalService handles internal Raft cluster communication
    #[derive(Debug, Clone)]
    pub struct RaftClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl RaftClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> RaftClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> RaftClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            RaftClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Vote handles vote requests between Raft nodes during leader election
        pub async fn vote(
            &mut self,
            request: impl tonic::IntoRequest<super::VoteReq>,
        ) -> std::result::Result<tonic::Response<super::VoteRsp>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/raft.Raft/Vote");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("raft.Raft", "Vote"));
            self.inner.unary(req, path, codec).await
        }
        /// AppendEntries handles call related to append entries RPC
        pub async fn append_entries(
            &mut self,
            request: impl tonic::IntoRequest<super::AppendEntriesReq>,
        ) -> std::result::Result<
            tonic::Response<super::AppendEntriesRsp>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/raft.Raft/AppendEntries");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("raft.Raft", "AppendEntries"));
            self.inner.unary(req, path, codec).await
        }
        /// StreamAppend handles streaming append entries for pipeline replication
        pub async fn stream_append(
            &mut self,
            request: impl tonic::IntoStreamingRequest<Message = super::AppendEntriesReq>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::AppendEntriesRsp>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/raft.Raft/StreamAppend");
            let mut req = request.into_streaming_request();
            req.extensions_mut().insert(GrpcMethod::new("raft.Raft", "StreamAppend"));
            self.inner.streaming(req, path, codec).await
        }
        /// Snapshot handles install snapshot RPC
        pub async fn snapshot(
            &mut self,
            request: impl tonic::IntoStreamingRequest<Message = super::SnapshotReq>,
        ) -> std::result::Result<tonic::Response<super::SnapshotRsp>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/raft.Raft/Snapshot");
            let mut req = request.into_streaming_request();
            req.extensions_mut().insert(GrpcMethod::new("raft.Raft", "Snapshot"));
            self.inner.client_streaming(req, path, codec).await
        }
        /// AddLearner adds a new learner node to the Raft cluster
        pub async fn add_learner(
            &mut self,
            request: impl tonic::IntoRequest<super::AddLearnerReq>,
        ) -> std::result::Result<tonic::Response<super::MembershipRsp>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/raft.Raft/AddLearner");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("raft.Raft", "AddLearner"));
            self.inner.unary(req, path, codec).await
        }
        /// ChangeMembership modifies the cluster membership configuration
        pub async fn change_membership(
            &mut self,
            request: impl tonic::IntoRequest<super::ChangeMembershipReq>,
        ) -> std::result::Result<tonic::Response<super::MembershipRsp>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/raft.Raft/ChangeMembership",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("raft.Raft", "ChangeMembership"));
            self.inner.unary(req, path, codec).await
        }
        /// Metrics retrieves cluster metrics and status information
        pub async fn metrics(
            &mut self,
            request: impl tonic::IntoRequest<()>,
        ) -> std::result::Result<tonic::Response<super::MetricsRsp>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/raft.Raft/Metrics");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("raft.Raft", "Metrics"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod raft_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with RaftServer.
    #[async_trait]
    pub trait Raft: std::marker::Send + std::marker::Sync + 'static {
        /// Vote handles vote requests between Raft nodes during leader election
        async fn vote(
            &self,
            request: tonic::Request<super::VoteReq>,
        ) -> std::result::Result<tonic::Response<super::VoteRsp>, tonic::Status>;
        /// AppendEntries handles call related to append entries RPC
        async fn append_entries(
            &self,
            request: tonic::Request<super::AppendEntriesReq>,
        ) -> std::result::Result<
            tonic::Response<super::AppendEntriesRsp>,
            tonic::Status,
        >;
        /// Server streaming response type for the StreamAppend method.
        type StreamAppendStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::AppendEntriesRsp, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// StreamAppend handles streaming append entries for pipeline replication
        async fn stream_append(
            &self,
            request: tonic::Request<tonic::Streaming<super::AppendEntriesReq>>,
        ) -> std::result::Result<
            tonic::Response<Self::StreamAppendStream>,
            tonic::Status,
        >;
        /// Snapshot handles install snapshot RPC
        async fn snapshot(
            &self,
            request: tonic::Request<tonic::Streaming<super::SnapshotReq>>,
        ) -> std::result::Result<tonic::Response<super::SnapshotRsp>, tonic::Status>;
        /// AddLearner adds a new learner node to the Raft cluster
        async fn add_learner(
            &self,
            request: tonic::Request<super::AddLearnerReq>,
        ) -> std::result::Result<tonic::Response<super::MembershipRsp>, tonic::Status>;
        /// ChangeMembership modifies the cluster membership configuration
        async fn change_membership(
            &self,
            request: tonic::Request<super::ChangeMembershipReq>,
        ) -> std::result::Result<tonic::Response<super::MembershipRsp>, tonic::Status>;
        /// Metrics retrieves cluster metrics and status information
        async fn metrics(
            &self,
            request: tonic::Request<()>,
        ) -> std::result::Result<tonic::Response<super::MetricsRsp>, tonic::Status>;
    }
    /// InternalService handles internal Raft cluster communication
    #[derive(Debug)]
    pub struct RaftServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> RaftServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for RaftServer<T>
    where
        T: Raft,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/raft.Raft/Vote" => {
                    #[allow(non_camel_case_types)]
                    struct VoteSvc<T: Raft>(pub Arc<T>);
                    impl<T: Raft> tonic::server::UnaryService<super::VoteReq>
                    for VoteSvc<T> {
                        type Response = super::VoteRsp;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::VoteReq>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Raft>::vote(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = VoteSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/raft.Raft/AppendEntries" => {
                    #[allow(non_camel_case_types)]
                    struct AppendEntriesSvc<T: Raft>(pub Arc<T>);
                    impl<T: Raft> tonic::server::UnaryService<super::AppendEntriesReq>
                    for AppendEntriesSvc<T> {
                        type Response = super::AppendEntriesRsp;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::AppendEntriesReq>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Raft>::append_entries(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = AppendEntriesSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/raft.Raft/StreamAppend" => {
                    #[allow(non_camel_case_types)]
                    struct StreamAppendSvc<T: Raft>(pub Arc<T>);
                    impl<
                        T: Raft,
                    > tonic::server::StreamingService<super::AppendEntriesReq>
                    for StreamAppendSvc<T> {
                        type Response = super::AppendEntriesRsp;
                        type ResponseStream = T::StreamAppendStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                tonic::Streaming<super::AppendEntriesReq>,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Raft>::stream_append(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = StreamAppendSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/raft.Raft/Snapshot" => {
                    #[allow(non_camel_case_types)]
                    struct SnapshotSvc<T: Raft>(pub Arc<T>);
                    impl<
                        T: Raft,
                    > tonic::server::ClientStreamingService<super::SnapshotReq>
                    for SnapshotSvc<T> {
                        type Response = super::SnapshotRsp;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<tonic::Streaming<super::SnapshotReq>>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Raft>::snapshot(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SnapshotSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.client_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/raft.Raft/AddLearner" => {
                    #[allow(non_camel_case_types)]
                    struct AddLearnerSvc<T: Raft>(pub Arc<T>);
                    impl<T: Raft> tonic::server::UnaryService<super::AddLearnerReq>
                    for AddLearnerSvc<T> {
                        type Response = super::MembershipRsp;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::AddLearnerReq>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Raft>::add_learner(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = AddLearnerSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/raft.Raft/ChangeMembership" => {
                    #[allow(non_camel_case_types)]
                    struct ChangeMembershipSvc<T: Raft>(pub Arc<T>);
                    impl<T: Raft> tonic::server::UnaryService<super::ChangeMembershipReq>
                    for ChangeMembershipSvc<T> {
                        type Response = super::MembershipRsp;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ChangeMembershipReq>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Raft>::change_membership(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ChangeMembershipSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/raft.Raft/Metrics" => {
                    #[allow(non_camel_case_types)]
                    struct MetricsSvc<T: Raft>(pub Arc<T>);
                    impl<T: Raft> tonic::server::UnaryService<()> for MetricsSvc<T> {
                        type Response = super::MetricsRsp;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(&mut self, request: tonic::Request<()>) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Raft>::metrics(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = MetricsSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for RaftServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "raft.Raft";
    impl<T> tonic::server::NamedService for RaftServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
